apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: urlshortener   # lowercase only
  namespace: m-aamirmalick-dev
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: urlshortener-build
  namespace: m-aamirmalick-dev
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: "https://github.com/Aamirmalick/URL-Shortener.git"
      ref: main
    contextDir: "."
  strategy:
    type: Docker
    dockerStrategy: {}
  output:
    to:
      kind: ImageStreamTag
      name: "urlshortener:latest"
  successfulBuildsHistoryLimit: 0
  failedBuildsHistoryLimit: 1
  triggers:
    - type: ConfigChange
    - type: ImageChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlshortener
  namespace: m-aamirmalick-dev
spec:
  replicas: 1
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: urlshortener
  template:
    metadata:
      labels:
        app: urlshortener
    spec:
      containers:
        - name: urlshortener
          image: image-registry.openshift-image-registry.svc:5000/m-aamirmalick-dev/urlshortener:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "1"
              memory: "1Gi"
            limits:
              cpu: "1"
              memory: "1Gi"
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: urlshortener-service
  namespace: m-aamirmalick-dev
spec:
  selector:
    app: urlshortener
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: urlshortener-route
  namespace: m-aamirmalick-dev
spec:
  to:
    kind: Service
    name: urlshortener-service
  port:
    targetPort: 8080
  tls:
    termination: edge
